### PR TITLE
UI changes w/ Tailwind.css

### PR DESCRIPTION
**Pull request by Zeishiin**
Up from previous PR, on the right branch this time.

### CODE REVIEW

**Comment by ishaan010** [comment]
OK just about to check your changes

**Comment by ishaan010** [comment]
Wow! this was great. But just one thing.
image

It's not mobile friendly. Sorry can not take it But really it was good if viewed from a laptop,
but not for mobile. If you still like to help then you can do it by making it mobile first.

**Comment by Zeishiin** [comment]
Completely forgot about it, I'll have a look.

**Comment by ishaan010** [comment]
OK thanks for your help

**Pull request merged**
