### PR TITLE
add layout 

### PR DESCRIPTION
**Pull request by ngdream**
now we don't have to write everytime the same footer

### CODE REVIEW

**Comment by ishaan010** [comment]
So this will not be like making a website from scratch, but using github right? 

I'm so bad at using github you know 😢

**Comment by ngdream** [comment]
> So this will not be like making a website from scratch, but using github right?
> 
> I'm so bad at using github for this you know

don't worry about this 
It will greatly facilitate the contribution and if you do not understand I can free myself to help you

**Comment by ngdream** [comment]
bro you can read this about use github  page  with jekyll http://jekyllrb.com/docs/pages/

**Comment by ishaan010** [comment]
Thanks a lot and quick thing on where you live? I live in India so like different time zones

**Comment by ishaan010** [comment]
Oh and make a PR at the branch with your name so I can check how it looks

**Comment by ngdream** [comment]
okay i will make a pull request to another branch bro

**Pull request closed without merging**
