### PR TITLE
Minor Responsive Adjustements 

### PR DESCRIPTION
**Pull request by Zeishiin**

### CODE REVIEW

**Comment by ishaan010** [comment]
Sorry for such a late accept😔

**Comment by ishaan010** [comment]
I think you should give up it's of no use
image
Really appreciated your hard work.

**Comment by ishaan010** [comment]
If you have given you then tell, so I can delete the branch

**Comment by Zeishiin** [comment]
Tested on 3 browsers, it's always on point. 

image

**Comment by ishaan010** [comment]
Oh! but on opera it's not? Wait let me test it on chrome

**Comment by Zeishiin** [comment]
Tested on : 
- Chrome
- Firefox 
- Opera GX

**Comment by ishaan010** [comment]
image
Will it looks like iPhone SE is having bugs

**Comment by Zeishiin** [comment]
Not on my end. That's quite strange. 
image

**Comment by ishaan010** [comment]
Sorry net went out.
OK so this is happening on my end so I am just going to add it to the main branch, but then I also need to add it to others, or do you want to do it? You can just say no if you don't want to.

**Comment by Zeishiin** [comment]
What do you mean?

**Comment by ishaan010** [comment]
I mean that do you want to change the style of other we pages or not.

**Comment by Zeishiin** [comment]
Didn't pay attention to the others, but yeah I'll have a look on my free time.

**Comment by ishaan010** [comment]
I mean do you want to make the changes on the other we pages or not

**Comment by ishaan010** [comment]
OK but I have already got 1000 people for around the world! Visiting my site!

**Pull request merged**
